'use strict';
const $=id=>document.getElementById(id);
let config=HeatLab.defaults(),grid=null,frame=null,worker=null,running=false,building=false,desiredRun=false,yaw=.55,pitch=.65,loadResolve=null,loadReject=null;
const fieldGroups=[['锅面、空气与翻面',[
 ['initial','初始温度','°C',1],['panTemperature','锅面温度','°C',1],['airTemperature','空气温度','°C',1],['contactH','锅面换热系数','W/(m² K)',1],['airH','空气换热系数','W/(m² K)',1],['flipTimes','翻面时刻','秒，逗号分隔；留空不翻面',1]
]],['牛排形状',[
 ['length','名义长度','mm',1000],['width','名义宽度','mm',1000],['thickness','厚度','mm',1000],['exponent','圆润指数','2–4；平面上下表面',1],['asymmetry','轮廓变化','0–0.15',1]
]],['网格与材料',[
 ['across','厚度网格数','8–32；先用 12',1],['end','模拟时长','s',1],['k','导热系数','W/(m K)',1],['rho','密度','kg/m³',1],['cp','比热容','J/(kg K)',1]
]]];
for(const [title,fields] of fieldGroups){const group=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent=title;group.append(legend);for(const [key,label,unit] of fields){const row=document.createElement('div');row.className='field'+(key==='flipTimes'?' full':'');const lab=document.createElement('label');lab.htmlFor='input-'+key;lab.textContent=label;const small=document.createElement('small');small.textContent=unit;lab.append(small);const input=document.createElement('input');input.id='input-'+key;input.name=key;if(key==='flipTimes'){input.type='text';input.placeholder='例如 120, 240';}else{input.type='number';input.step='any';input.required=true;input.inputMode='decimal';}row.append(lab,input);group.append(row);}$('fields').append(group);}
function fill(c){for(const [,fields] of fieldGroups)for(const [key,,,scale] of fields)$('input-'+key).value=key==='flipTimes'?c[key].join(', '):Number((c[key]*scale).toPrecision(10));}
function readConfig(){const c=HeatLab.defaults();for(const [,fields] of fieldGroups)for(const [key,,,scale] of fields){const raw=$('input-'+key).value.trim();c[key]=key==='flipTimes'?(raw?raw.split(/[,，]/).map(x=>x.trim()?Number(x):NaN):[]):raw?Number(raw)/scale:NaN;}HeatLab.validate(c);return c;}
function showTab(name){document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==name);document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===name);b.setAttribute('aria-current',b.dataset.tab===name?'page':'false');});window.scrollTo(0,0);if(name==='explore')requestAnimationFrame(draw);}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
function error(message){$('error').textContent=message;$('error').hidden=false;}
function clearError(){$('error').hidden=true;}
function build(c){HeatLab.validate(c);if(loadReject)loadReject(Error('已取消'));worker?.terminate();config=JSON.parse(JSON.stringify(c));building=true;running=desiredRun=false;grid=frame=null;clearError();$('status').textContent='正在创建三维网格…';$('minimum').textContent='—';$('clock').textContent=`0 / ${config.end} s`;$('progress').value=0;$('progress').max=config.end;$('panPower').textContent=$('airPower').textContent='— W';$('nextFlip').textContent='—';$('flipCount').textContent='已翻面 0 次';$('run').textContent='开始模拟';$('coldPosition').textContent='正在初始化';$('run').disabled=true;$('reset').disabled=true;document.querySelectorAll('[data-export]').forEach(b=>b.disabled=true);draw();
 const result=new Promise((resolve,reject)=>{loadResolve=resolve;loadReject=reject;});const active=worker=new Worker('./worker.js');
 active.onerror=e=>{if(worker!==active)return;failure(e.message||'无法启动计算。');};
 active.onmessage=({data:m})=>{if(worker!==active)return;if(m.type==='error'){failure(m.message);return;}if(m.type==='ready'){grid=m.grid;building=false;fill(config);try{localStorage.setItem('heat-lab-iphone-v1',JSON.stringify(config));}catch{}configureSlice();}$('run').disabled=false;$('reset').disabled=false;document.querySelectorAll('[data-export]').forEach(b=>b.disabled=false);frame=m;running=m.running;render();if(m.type==='ready'){loadResolve?.({ready:true,cells:grid.inside.length});loadResolve=loadReject=null;}};
 active.postMessage({type:'init',config});return result;
}
function failure(message){building=running=desiredRun=false;$('status').textContent='计算未完成';$('run').disabled=true;$('reset').disabled=false;error(message);loadReject?.(Error(message));loadResolve=loadReject=null;}
function setRun(value){if(!grid||building)return;desiredRun=value;worker.postMessage({type:value?'run':'pause'});$('run').textContent=value?'暂停':'继续';}
$('run').onclick=()=>{if(frame?.time>=config.end){build(config).catch(()=>{});return;}setRun(!desiredRun);};$('reset').onclick=()=>build(config).catch(()=>{});
$('configForm').onsubmit=e=>{e.preventDefault();try{const c=readConfig();showTab('explore');build(c).catch(()=>{});}catch(e){error(e.message);}};
$('steakPreset').onclick=()=>fill(HeatLab.defaults());$('ovenPreset').onclick=()=>{const c=HeatLab.defaults();c.contactH=0;c.airTemperature=180;c.airH=25;c.flipTimes=[];fill(c);};
function render(){if(!grid||!frame)return;const f=frame,flips=f.row[7];if(f.time>=config.end)desiredRun=false;$('status').textContent=f.time>=config.end?'模拟完成':running?'正在计算':f.time===0?'准备就绪':'已暂停';$('clock').textContent=`${f.time.toFixed(1)} / ${config.end} s`;$('progress').max=config.end;$('progress').value=f.time;$('run').textContent=running?'暂停':f.time>=config.end?'重新计算':f.time?'继续':'开始模拟';$('minimum').textContent=f.stats[0].toFixed(2);$('coldPosition').textContent=f.time?`冷点 x ${(f.row[4]*1000).toFixed(1)} · y ${(f.row[5]*1000).toFixed(1)} · z ${(f.row[6]*1000).toFixed(1)} mm`:'初始内部温度均匀';$('nextFlip').textContent=Number.isFinite(f.nextFlip)?`${f.nextFlip} s`:'无';$('flipCount').textContent=`已翻面 ${flips} 次`;$('orientation').textContent=`${flips%2?'B':'A'} 面朝下`;$('panPower').textContent=`${f.row[8]>=0?'+':''}${f.row[8].toFixed(1)} W`;$('airPower').textContent=`${f.row[9]>=0?'+':''}${f.row[9].toFixed(1)} W`;
 $('diagnostics').textContent=`${grid.nx} × ${grid.ny} × ${grid.nz} 网格 · ${grid.geometry.markers.length} 表面标记\n网格间距 ${(grid.h*1000).toFixed(3)} mm · 步长 ≤ ${grid.stableDt.toPrecision(3)} s\n已计算 ${f.steps} 步\n内部平均 ${f.stats[2].toFixed(2)} °C · 最高 ${f.stats[1].toFixed(2)} °C\n掩膜能量 ${f.row[10].toFixed(1)} J\n边界累计输入 ${f.row[11].toFixed(1)} J\n数值计算域交换 ${f.row[12].toFixed(1)} J\n能量记账残差 ${f.row[13].toExponential(2)} J`;draw();}
function configureSlice(){if(!grid)return;const a=Number($('plane').value),n=[grid.nz,grid.ny,grid.nx][a];$('slice').max=n-1;$('slice').value=Math.floor(n/2);}
$('sliceView').onchange=drawSlice;
$('plane').onchange=()=>{configureSlice();drawSlice();};$('slice').oninput=drawSlice;$('coldSlice').onclick=()=>{if(!frame)return;$('plane').value='0';configureSlice();$('slice').value=Math.floor(frame.stats[3]/(grid.nx*grid.ny));drawSlice();};
function context(id){const canvas=$(id),w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return null;const d=Math.min(devicePixelRatio||1,3);canvas.width=Math.round(w*d);canvas.height=Math.round(h*d);const ctx=canvas.getContext('2d');ctx.setTransform(d,0,0,d,0,0);return{ctx,w,h};}
function temperatureRange(){const values=frame?frame.surface:[config.initial];let low=Infinity,high=-Infinity;for(const t of values){low=Math.min(low,t);high=Math.max(high,t);}if(high-low<.1)high=low+1;return[low,high];}
function viewChanged(){const temperature=$('surfaceView').value==='temperature';$('boundaryLegend').hidden=temperature;$('surfaceScale').hidden=!temperature;$('surfaceNote').hidden=!temperature;drawShape();}
$('surfaceView').onchange=viewChanged;
function draw(){drawShape();drawSlice();}
function drawShape(){const output=context('shape');if(!output||!grid)return;const {ctx,w,h}=output,g=grid.geometry,sign=frame&&frame.row[7]%2?-1:1,scale=Math.min(w,h*1.65)*.82/Math.max(config.length*(1+config.asymmetry),config.width*(1+config.asymmetry));
 const surfaceRange=temperatureRange();$('surfaceLow').textContent=`${surfaceRange[0].toFixed(1)} °C`;$('surfaceHigh').textContent=`${surfaceRange[1].toFixed(1)} °C`;
 const project=v=>{const x=Math.cos(yaw)*v[0]-Math.sin(yaw)*v[1]*sign,y=Math.sin(yaw)*v[0]+Math.cos(yaw)*v[1]*sign;return[w/2+x*scale,h/2-(Math.sin(pitch)*y+Math.cos(pitch)*v[2]*sign)*scale,Math.cos(pitch)*y-Math.sin(pitch)*v[2]*sign];};const points=g.vertices.map(project),parity=frame?frame.row[7]%2:0;
 g.quads.map((q,i)=>({q,i,depth:q.reduce((s,j)=>s+points[j][2],0)})).sort((a,b)=>b.depth-a.depth).forEach(({q,i})=>{ctx.beginPath();q.forEach((j,k)=>k?ctx.lineTo(points[j][0],points[j][1]):ctx.moveTo(points[j][0],points[j][1]));ctx.closePath();const weight=grid.contact[parity][i];ctx.fillStyle=$('surfaceView').value==='temperature'&&frame?colour((frame.surface[i]-surfaceRange[0])/(surfaceRange[1]-surfaceRange[0])):`rgb(${60+184*weight},${175+5*weight},${167-88*weight})`;ctx.fill();ctx.strokeStyle='#23535b';ctx.lineWidth=.55;ctx.stroke();});
 if(frame?.time){const p=project(frame.row.slice(4,7));ctx.strokeStyle='#fff';ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(p[0]-6,p[1]);ctx.lineTo(p[0]+6,p[1]);ctx.moveTo(p[0],p[1]-6);ctx.lineTo(p[0],p[1]+6);ctx.stroke();}
}
const colours=[[25,62,104],[20,143,154],[165,208,160],[241,207,112],[184,61,56]];
function colour(t){const f=Math.max(0,Math.min(1,t))*4,i=Math.min(3,Math.floor(f)),a=f-i;return`rgb(${colours[i].map((v,j)=>Math.round(v*(1-a)+colours[i+1][j]*a)).join(',')})`;}
function drawSlice(){const output=context('heatmap');if(!output||!grid||!frame)return;const cooked=$('sliceView').value==='doneness';$('temperatureScale').hidden=cooked;$('donenessLegend').hidden=!cooked;$('donenessNote').hidden=!cooked;const {ctx,w,h}=output,a=Number($('plane').value),at=Number($('slice').value),n1=a===2?grid.ny:grid.nx,n2=a===0?grid.ny:grid.nz,scale=Math.min((w-30)/n1,(h-30)/n2),left=(w-n1*scale)/2,top=(h-n2*scale)/2;let low=Math.min(config.initial,config.airTemperature,config.contactH>0?config.panTemperature:config.airTemperature),high=Math.max(config.initial,config.airTemperature,config.contactH>0?config.panTemperature:config.airTemperature);if(high===low)high=low+1;$('low').textContent=`${low} °C`;$('high').textContent=`${high} °C`;
 const coord=[grid.z0,grid.y0,grid.x0][a]+(at+.5)*grid.h;$('sliceLabel').textContent=`${['z','y','x'][a]} = ${(coord*1000).toFixed(2)} mm · 牛排坐标`;let cold=null;
 for(let v=0;v<n2;v++)for(let u=0;u<n1;u++){const i=a===0?(at*grid.ny+v)*grid.nx+u:a===1?(v*grid.ny+at)*grid.nx+u:(v*grid.ny+u)*grid.nx+at;if(!grid.inside[i])continue;ctx.fillStyle=cooked?HeatLabDoneness.color(frame.peak[i]):colour((frame.field[i]-low)/(high-low));ctx.fillRect(left+u*scale,top+(n2-1-v)*scale,scale+.3,scale+.3);if(i===frame.stats[3]&&frame.time)cold=[left+(u+.5)*scale,top+(n2-v-.5)*scale];}
 if(cold){ctx.strokeStyle='white';ctx.lineWidth=2;ctx.beginPath();ctx.arc(...cold,Math.max(4,scale),0,Math.PI*2);ctx.stroke();}ctx.fillStyle='#a2b8bf';ctx.font='13px -apple-system, sans-serif';ctx.fillText(`${['y','z','z'][a]} ↑`,10,17);ctx.fillText(`${['x','x','y'][a]} →`,w-35,h-8);
}
let pointer=null;$('shape').onpointerdown=e=>{pointer={x:e.clientX,y:e.clientY};$('shape').setPointerCapture(e.pointerId);};$('shape').onpointermove=e=>{if(!pointer)return;yaw+=(e.clientX-pointer.x)/150;pitch=Math.max(-1.4,Math.min(1.4,pitch+(e.clientY-pointer.y)/150));pointer={x:e.clientX,y:e.clientY};drawShape();};$('shape').onpointerup=$('shape').onpointercancel=()=>pointer=null;
window.addEventListener('resize',draw);document.addEventListener('visibilitychange',()=>{if(document.hidden&&worker)setRun(false);});window.addEventListener('pagehide',()=>{if(worker)setRun(false);});
async function shareExport(kind){try{const data=HeatLabExport.exportData(kind,config,grid,frame),file=new File([data.content],data.name,{type:data.type});if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:data.name});}else{const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=data.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}}catch(e){if(e.name!=='AbortError')error('导出失败：'+e.message);}}
document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>shareExport(b.dataset.export));
$('install').onclick=$('installMethod').onclick=()=>$('installDialog').showModal();$('closeInstall').onclick=()=>$('installDialog').close();
try{const saved=JSON.parse(localStorage.getItem('heat-lab-iphone-v1'));if(saved){if(saved.contactDepth===0)saved.contactH=0;delete saved.contactDepth;saved.flatFaces=true;HeatLab.validate(saved);config=saved;}}catch{}fill(config);build(config).catch(()=>{});
if('serviceWorker' in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
// Optional browser WebMCP actions use the same app state as the visible interface.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();for(const tool of [{name:'read_steak_simulation',title:'读取牛排模拟',description:'Read the displayed simulation state without changing it.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||Object.keys(input).length)throw Error('No parameters accepted');return{ready:!!grid,time:frame?.time,core:frame?.stats.slice(0,3),flips:frame?.row[7],running,config};}},{name:'configure_steak_simulation',title:'设置牛排模拟',description:'Apply complete SI-unit configuration, reset results and wait for the new grid. Does not start time stepping.',inputSchema:{type:'object',properties:{config:{type:'object'}},required:['config'],additionalProperties:false},annotations:{readOnlyHint:false},async execute(input){if(!input||Object.keys(input).some(k=>k!=='config')||!input.config)throw Error('config required');HeatLab.validate(input.config);showTab('explore');return await build(input.config);}}])try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
